### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by KjellKod** [copperspice/cs_signal#1]
Hi, 

I would love some documention and examples in Wiki or in a readme.  Maybe a minimal effort would be to link to this documention?: http://www.copperspice.com/docs/cs_signal/lib-overview.html

Thanks
Kjell Hedstrom

**Comment by agserm** [comment]
Thanks for your suggestion and report. I believe this was resolved by d9a1df8. Please let us know any other suggestions or enhancements you would like to see.
