### ISSUE TITLE
Problems using vs2019 in Release mode

### ISSUE THREAD

**Issue by Hurleyworks** [copperspice/cs_signal#13]
Hi.

Thanks for making this project and your YouTube videos available! I appreciate your efforts!!!

I am hitting a problem with cs_signal compiled with vs2019. Everything works as expected in Debug mode. But in Release mode when signals/slots have the same signature the incorrect slot can be called. . My guess is this is due to some compiler optimization.

I made a minimalist version of my project that demonstrates the problem
https://github.com/Hurleyworks/MVC

Running in Debug you can see that each signal generated by a button press goes to the correct slot.  But in Release mode, if you press the Send 1 button, for example, all 4 slots with the same signature  in Model get called 

-Steve

**Comment by agserm** [comment]
We will be looking at this later in the week. Thank you for your report.

**Comment by agserm** [comment]
This comment was recently reviewed, unable to repeat. Please reopen with a reproduction test case if the issue still exists.
