### ISSUE TITLE
reliable source download

### ISSUE THREAD

**Issue by ericLemanissier** [copperspice/cs_signal#15]
As mentionned in https://github.com/copperspice/cs_signal/issues/14#issuecomment-776098982, this project does not uses tags. It does use some kind of versionning though, as can be seen on https://github.com/copperspice/cs_signal/commit/6add8228fee3a2aff537500d654ba2e424968be8#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
There is currently no documented way to download a given version of this library. This is a problem because it prevents reliable use of this library.
Some possibilities:

- remove version numbers from cmake files, and clearly documents that it's some kind of "live at head"
- create tags
- host source tarballs somewhere, and document them

These repos have the same problem, but I'm not duplicating the issue: https://github.com/copperspice/cs_string, https://github.com/copperspice/cs_libguarded, https://github.com/copperspice/cs_paint

**Comment by agserm** [comment]
> host source tarballs somewhere, and document them

Our download page is mentioned in our documentation and there is a link on our main index page. Source tarballs have been available for every project from the beginning. The files for CsSignal are located here: http://download.copperspice.com/cs_signal/source/

**Comment by ericLemanissier** [comment]
Indeed I missed that page, that's on me for not reading documentation with enough attention..
Still, the fact that it contains only the last version prevents makes the situation sort of "live at head", or is there an archive of previous versions that I missed ?
