### ISSUE TITLE
Wrong target in src/signal.cmake

### ISSUE THREAD

**Issue by jvoosten** [copperspice/cs_signal#18]
While compilingCsSignal on Windows, CMake complained about this:

~~~
  Cannot specify link options for target "CsCore" which is not built by this
  project.
~~~

On line 40 in src/signal.cmake it says "target_link_options(**CsCore** ...",  not CsSignal.

**Comment by agserm** [comment]
Thanks for reporting this. It has been resolved in commit 8d9eb0a.
