### ISSUE TITLE
Can I connect/disconnect to the same signal in slot?

### ISSUE THREAD

**Issue by lexxmark** [copperspice/cs_signal#5]

**Comment by agserm** [comment]
I believe you are asking if you can connect or disconnect a signal/slot connection in the slot method.

The answer is yes, this is supported. A slot may be removed from the connection list at any time, even while that slot is executing. A connection may also be added at any time. If a signal is currently being emitted when the connection is added, the slot may or may not be called for that particular signal activation.

Let me know if there is any additional information you need on this topic.

**Comment by lexxmark** [comment]
Oh, I see you use some sophisticated rcu_list class to store receivers.
Do you have some brief estimations how many new/delete per connect/disconnect/activate?

**Comment by agserm** [comment]
Yes, the rcu_list from libGuarded is used in cs_signal to support concurrent modifications to the list while a signal activation is in process.

I have not profiled the exact numbers, but I believe that each operation on the list (connect / disconnect / activate ) requires one new/delete pair. In addition, a connect requires a new to store the new information and a disconnect will do the corresponding delete.
