### ISSUE TITLE
Add benchmark to  https://github.com/NoAvailableAlias/signal-slot-benchmarks/

### ISSUE THREAD

**Issue by Ultrafeel** [copperspice/cs_signal#6]

**Comment by NoAvailableAlias** [comment]
I've started evaluating this lib and will work on getting it integrated into the rework branch of signal-slot-benchmarks.

**Comment by agserm** [comment]
Thanks for your interest and being willing to add CsSignal to the test suite. We are glad to help out.

**Comment by agserm** [comment]
Closing due to no response.
